language: cpp
compiler:
 - gcc
before_install:
 - export DEVKITPRO=/home/travis/devkitPro
 - export DEVKITARM=${DEVKITPRO}/devkitARM
 - export CTRULIB=${DEVKITPRO}/libctru
 - export GL3DS=/home/travis/gl3ds
 - sh .travis-deps.sh
script:
 - sh .travis-build.sh
