os:
  - linux

language: cpp

sudo: required
services:
  - docker

script:
  - docker build -t cpp3ds .

before_deploy:
  - export RELEASE_FILENAME=cpp3ds-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.xz
  - docker run --rm -v "$PWD":/usr/build -w /opt cpp3ds sh /usr/build/.build.sh /usr/build/$RELEASE_FILENAME
  - sudo chmod 777 $RELEASE_FILENAME

deploy:
  provider: releases
  api_key:
    secure: B+KWmLSo9LDh4P+8JGZF6RUPu5WQCV6RwXg87X44UXswDdbqYvBMA884KU8bWxDq70CtQKw1AwzK8z5KFDCLGG0jL41d1BEblXHNi4Xu+vm3SCG+EQ5M9wFV/9rX8vXC+UKMSzFeagL33ATa0tBm1BcpR6JtdHoWGNYjeG29a2o=
  file: $RELEASE_FILENAME
  skip_cleanup: true
  on:
    tags: true
    repo: cpp3ds/cpp3ds
